spring.application.name=unimate-backend

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/unimate_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}

# Hibernate/JPA DDL Properties
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# JWT Configuration/Auth
jwt.secret=pwUTSY6DjbOlO5ZXuCu7Ig9bsA/uZe01eOzc3jxyKk4=
jwt.expiration-ms=86400000
logging.level.org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer=ERROR